Importing the libraries for Data Modelling and Transformation

In [ ]:
import numpy as np
import pandas as pd

Loading the datasets

In [ ]:
ad_events = pd.read_csv(r'/content/ad_events.csv')
ads = pd.read_csv(r'/content/ads.csv')
campaigns = pd.read_csv(r'/content/campaigns.csv')
users = pd.read_csv(r'/content/users.csv')

Starting EDA for ad_events

In [ ]:
ad_events.head()

,event_id,ad_id,user_id,timestamp,day_of_week,time_of_day,event_type
0,1,197,2359b,2025-07-26 00:19:56,Saturday,Night,Like
1,2,51,f9c67,2025-06-15 08:28:07,Sunday,Morning,Share
2,3,46,5b868,2025-06-27 00:40:02,Friday,Night,Impression
3,4,166,3d440,2025-06-05 19:20:45,Thursday,Evening,Impression
4,5,52,68f1a,2025-07-22 08:30:29,Tuesday,Morning,Impression

In [ ]:
ad_events.tail()

,event_id,ad_id,user_id,timestamp,day_of_week,time_of_day,event_type
399995,399996,132,3cb8c,2025-08-01 22:36:54,Friday,Evening,Impression
399996,399997,200,fe0e3,2025-05-31 14:53:18,Saturday,Afternoon,Impression
399997,399998,2,a08c1,2025-07-27 13:39:51,Sunday,Afternoon,Click
399998,399999,109,4f0cf,2025-05-16 02:38:23,Friday,Night,Impression
399999,400000,63,2c11d,2025-06-15 12:06:28,Sunday,Afternoon,Impression

In [ ]:
ad_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   event_id     400000 non-null  int64
 1   ad_id        400000 non-null  int64
 2   user_id      400000 non-null  object
 3   timestamp    400000 non-null  object
 4   day_of_week  400000 non-null  object
 5   time_of_day  400000 non-null  object
 6   event_type   400000 non-null  object
dtypes: int64(2), object(5)
memory usage: 21.4+ MB

In [ ]:
ad_events.describe()

            event_id          ad_id
count  400000.000000  400000.000000
mean   200000.500000     100.535965
std    115470.198175      57.775915
min         1.000000       1.000000
25%    100000.750000      51.000000
50%    200000.500000     101.000000
75%    300000.250000     151.000000
max    400000.000000     200.000000

In [ ]:
ad_events.isnull().sum()

event_id       0
ad_id          0
user_id        0
timestamp      0
day_of_week    0
time_of_day    0
event_type     0
dtype: int64

In [ ]:
ad_events.shape

(400000, 7)

In [ ]:
ad_events.duplicated().sum()

np.int64(0)

EDA for ads

In [ ]:
ads.head()

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,target_interests
0,1,28,Facebook,Video,Female,35-44,"art, technology"
1,2,33,Facebook,Stories,All,25-34,"travel, photography"
2,3,20,Instagram,Carousel,All,25-34,technology
3,4,28,Facebook,Stories,Female,25-34,news
4,5,24,Instagram,Image,Female,25-34,news

In [ ]:
ads.tail()

,ad_id,campaign_id,ad_platform,ad_type,target_gender,target_age_group,target_interests
195,196,12,Facebook,Stories,Male,35-44,"gaming, sports"
196,197,9,Facebook,Stories,All,All,"lifestyle, gaming"
197,198,34,Facebook,Video,All,35-44,"fitness, lifestyle"
198,199,15,Instagram,Video,Male,25-34,"art, news"
199,200,44,Instagram,Carousel,Male,18-24,photography

In [ ]:
ads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ad_id             200 non-null    int64
 1   campaign_id       200 non-null    int64
 2   ad_platform       200 non-null    object
 3   ad_type           200 non-null    object
 4   target_gender     200 non-null    object
 5   target_age_group  200 non-null    object
 6   target_interests  200 non-null    object
dtypes: int64(2), object(5)
memory usage: 11.1+ KB

In [ ]:
ads.describe()

            ad_id  campaign_id
count  200.000000   200.000000
mean   100.500000    25.125000
std     57.879185    13.713485
min      1.000000     1.000000
25%     50.750000    13.000000
50%    100.500000    25.000000
75%    150.250000    37.000000
max    200.000000    50.000000

In [ ]:
ads.shape

(200, 7)

In [ ]:
ads.isnull().sum()

ad_id               0
campaign_id         0
ad_platform         0
ad_type             0
target_gender       0
target_age_group    0
target_interests    0
dtype: int64

In [ ]:
ads.duplicated().sum()

np.int64(0)

EDA for campaigns

In [ ]:
campaigns.head()

,campaign_id,name,start_date,end_date,duration_days,total_budget
0,1,Campaign_1_Launch,25-05-2025,23-07-2025,59,24021.32
1,2,Campaign_2_Launch,16-04-2025,07-07-2025,82,79342.41
2,3,Campaign_3_Winter,04-05-2025,29-06-2025,56,14343.25
3,4,Campaign_4_Summer,04-06-2025,08-08-2025,65,45326.60
4,5,Campaign_5_Launch,11-07-2025,28-08-2025,48,68376.69

In [ ]:
campaigns.tail()

,campaign_id,name,start_date,end_date,duration_days,total_budget
45,46,Campaign_46_Winter,10-05-2025,07-08-2025,89,94023.76
46,47,Campaign_47_Launch,17-06-2025,03-09-2025,78,69493.36
47,48,Campaign_48_Winter,08-04-2025,01-06-2025,54,13842.07
48,49,Campaign_49_Winter,21-02-2025,17-05-2025,85,28962.34
49,50,Campaign_50_Summer,02-07-2025,03-08-2025,32,47274.70

In [ ]:
campaigns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    50 non-null     int64
 1   name           50 non-null     object
 2   start_date     50 non-null     object
 3   end_date       50 non-null     object
 4   duration_days  50 non-null     int64
 5   total_budget   50 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 2.5+ KB

In [ ]:
campaigns.describe()

       campaign_id  duration_days  total_budget
count     50.00000      50.000000     50.000000
mean      25.50000      66.040000  50718.475600
std       14.57738      16.380626  24576.018632
min        1.00000      32.000000   7918.040000
25%       13.25000      52.500000  31105.435000
50%       25.50000      69.500000  48053.655000
75%       37.75000      81.750000  71600.592500
max       50.00000      90.000000  98904.660000

In [ ]:
campaigns.isnull().sum()

campaign_id      0
name             0
start_date       0
end_date         0
duration_days    0
total_budget     0
dtype: int64

In [ ]:
campaigns.shape

(50, 6)

In [ ]:
campaigns.duplicated().sum()

np.int64(0)

EDA for users

In [ ]:
users.head()

,user_id,user_gender,user_age,age_group,country,location,interests
0,1.20E+01,Male,56,55-65,Japan,New Jeremy,"lifestyle, health"
1,5.00E+01,Female,17,16-17,Canada,Lake Juanville,"food, finance"
2,62,Female,16,16-17,France,Davidside,"photography, art, food"
3,67,Male,38,35-44,United States,East Gary,"travel, gaming, art"
4,7.00E+01,Male,23,18-24,United States,Audreyton,"photography, food"

In [ ]:
users.tail()

,user_id,user_gender,user_age,age_group,country,location,interests
9836,ffd56,Male,30,25-34,Japan,Lake Richardside,"news, gaming"
9837,ffd82,Female,41,35-44,Mexico,Vanessamouth,"technology, fitness, art"
9838,ffe0f,Male,31,25-34,Australia,Tonyaside,"fitness, gaming, news"
9839,ffed3,Male,47,45-54,United Kingdom,Kimberlyburgh,"health, news"
9840,fff7c,Male,33,25-34,United States,South Cynthiashire,lifestyle

In [ ]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9841 entries, 0 to 9840
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      9841 non-null   object
 1   user_gender  9841 non-null   object
 2   user_age     9841 non-null   int64
 3   age_group    9841 non-null   object
 4   country      9841 non-null   object
 5   location     9841 non-null   object
 6   interests    9841 non-null   object
dtypes: int64(1), object(6)
memory usage: 538.3+ KB

In [ ]:
users.describe()

          user_age
count  9841.000000
mean     27.627578
std       8.311541
min      16.000000
25%      21.000000
50%      26.000000
75%      32.000000
max      65.000000

In [ ]:
users.shape

(9841, 7)

In [ ]:
users.duplicated().sum()

np.int64(0)